name: Deploy Preview

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/*.yml'

env:
  NODE_VERSION: '22.21.1'
  PNPM_VERSION: '10.22.0'

permissions:
  contents: read
  deployments: write

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup
        with:
          node-version: ${{ env.NODE_VERSION }}
          pnpm-version: ${{ env.PNPM_VERSION }}

      - name: Install Vercel CLI
        run: pnpm add --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Set Vercel Environment Variables
        run: |
          vercel env rm DEBUG preview --yes --token=${{ secrets.VERCEL_TOKEN }} || true
          vercel env rm NEON_DATABASE_URL preview --yes --token=${{ secrets.VERCEL_TOKEN }} || true
          vercel env rm RESEND_API_KEY preview --yes --token=${{ secrets.VERCEL_TOKEN }} || true
          vercel env rm RESEND_FROM preview --yes --token=${{ secrets.VERCEL_TOKEN }} || true
          vercel env rm RESEND_ADMIN preview --yes --token=${{ secrets.VERCEL_TOKEN }} || true
          vercel env rm MICROCMS_SERVICE_DOMAIN preview --yes --token=${{ secrets.VERCEL_TOKEN }} || true
          vercel env rm MICROCMS_API_KEY preview --yes --token=${{ secrets.VERCEL_TOKEN }} || true
          vercel env rm NEXT_PUBLIC_RECAPTCHA_SITE_KEY preview --yes --token=${{ secrets.VERCEL_TOKEN }} || true
          vercel env rm RECAPTCHA_SECRET_KEY preview --yes --token=${{ secrets.VERCEL_TOKEN }} || true
          vercel env rm NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID preview --yes --token=${{ secrets.VERCEL_TOKEN }} || true
          echo -n "${{ secrets.DEBUG_PREVIEW }}" | vercel env add DEBUG preview --token=${{ secrets.VERCEL_TOKEN }}
          echo -n "${{ secrets.NEON_DATABASE_URL_PREVIEW }}" | vercel env add NEON_DATABASE_URL preview --token=${{ secrets.VERCEL_TOKEN }}
          echo -n "${{ secrets.RESEND_API_KEY_PREVIEW }}" | vercel env add RESEND_API_KEY preview --token=${{ secrets.VERCEL_TOKEN }}
          echo -n "${{ secrets.RESEND_FROM_PREVIEW }}" | vercel env add RESEND_FROM preview --token=${{ secrets.VERCEL_TOKEN }}
          echo -n "${{ secrets.RESEND_ADMIN_PREVIEW }}" | vercel env add RESEND_ADMIN preview --token=${{ secrets.VERCEL_TOKEN }}
          echo -n "${{ secrets.MICROCMS_SERVICE_DOMAIN_PREVIEW }}" | vercel env add MICROCMS_SERVICE_DOMAIN preview --token=${{ secrets.VERCEL_TOKEN }}
          echo -n "${{ secrets.MICROCMS_API_KEY_PREVIEW }}" | vercel env add MICROCMS_API_KEY preview --token=${{ secrets.VERCEL_TOKEN }}
          echo -n "${{ secrets.RECAPTCHA_SITE_KEY_PREVIEW }}" | vercel env add NEXT_PUBLIC_RECAPTCHA_SITE_KEY preview --token=${{ secrets.VERCEL_TOKEN }}
          echo -n "${{ secrets.RECAPTCHA_SECRET_KEY_PREVIEW }}" | vercel env add RECAPTCHA_SECRET_KEY preview --token=${{ secrets.VERCEL_TOKEN }}
          echo -n "${{ secrets.GOOGLE_TAG_MANAGER_ID_PREVIEW }}" | vercel env add NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID preview --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Verify Vercel Environment Variables
        run: |
          echo "Listing Vercel environment variables:"
          vercel env ls preview --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          DEBUG: ${{ secrets.DEBUG_PREVIEW }}
          NEON_DATABASE_URL: ${{ secrets.NEON_DATABASE_URL_PREVIEW }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY_PREVIEW }}
          RESEND_FROM: ${{ secrets.RESEND_FROM_PREVIEW }}
          RESEND_ADMIN: ${{ secrets.RESEND_ADMIN_PREVIEW }}
          MICROCMS_SERVICE_DOMAIN: ${{ secrets.MICROCMS_SERVICE_DOMAIN_PREVIEW }}
          MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY_PREVIEW }}
          NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${{ secrets.RECAPTCHA_SITE_KEY_PREVIEW }}
          RECAPTCHA_SECRET_KEY: ${{ secrets.RECAPTCHA_SECRET_KEY_PREVIEW }}
          NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID: ${{ secrets.GOOGLE_TAG_MANAGER_ID_PREVIEW }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          DEBUG: ${{ secrets.DEBUG_PREVIEW }}
          NEON_DATABASE_URL: ${{ secrets.NEON_DATABASE_URL_PREVIEW }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY_PREVIEW }}
          RESEND_FROM: ${{ secrets.RESEND_FROM_PREVIEW }}
          RESEND_ADMIN: ${{ secrets.RESEND_ADMIN_PREVIEW }}
          MICROCMS_SERVICE_DOMAIN: ${{ secrets.MICROCMS_SERVICE_DOMAIN_PREVIEW }}
          MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY_PREVIEW }}
          NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${{ secrets.RECAPTCHA_SITE_KEY_PREVIEW }}
          RECAPTCHA_SECRET_KEY: ${{ secrets.RECAPTCHA_SECRET_KEY_PREVIEW }}
          NEXT_PUBLIC_GOOGLE_TAG_MANAGER_ID: ${{ secrets.GOOGLE_TAG_MANAGER_ID_PREVIEW }}
